name: Run on push

on: 
  push:
    branches: [main]


jobs:
    run-script:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Execute run.sh file
               
              run: |
                chmod +x run.sh
                 ./run.sh